language: node_js
node_js:
  - "6"
  - "6.1"
before_script:
  - npm install -g jasmine
  - npm install -g istanbul
script:
  - npm run test
  - npm run test:coverage
after_success:
  - npm run coveralls
